### ISSUE TITLE
min(threads, len(os.sched_getaffinity(0))) not working, may be int(threads)?

### ISSUE THREAD

**Issue by jianshu93** [KGerhardt/multitrim#1]
Traceback (most recent call last):
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/bin/multitrim", line 8, in <module>
    sys.exit(main())
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/lib/python3.8/site-packages/multitrim/multitrim.py", line 888, in main
    threads = min(threads, len(os.sched_getaffinity(0)))
TypeError: '<' not supported between instances of 'int' and 'str'

**Comment by KGerhardt** [comment]
Yeah, that's gonna be it. I suggest using the --max flag, generally, to set
the number of processes, but I will fix threads.

**Comment by KGerhardt** [comment]
Fixed the threads issue.
