### ISSUE TITLE
module 'os' has no attribute 'sched_getaffinity' in macOS

### ISSUE THREAD

**Issue by lmrodriguezr** [KGerhardt/multitrim#5]
I'm getting the following error in macOS, even though I'm specifying the `--threads` flag:

```
Traceback (most recent call last):
  File "/Users/miguel/GitHub/multitrim/multitrim.py", line 1280, in <module>
    main()
  File "/Users/miguel/GitHub/multitrim/multitrim.py", line 1105, in main
    threads = min(threads, len(os.sched_getaffinity(0)))
AttributeError: module 'os' has no attribute 'sched_getaffinity'
```

**Comment by KGerhardt** [comment]
OK, I'll fix that up.
